#!/usr/bin/env python3
"""Materialize catalog strategies as runs; score robust Sharpe; write CSV summary."""

from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

_REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_REPO))

from tqg_client.lab_index import touch_run_index  # noqa: E402
from tqg_client.run_state import load_run_state, new_run_state, save_run_state  # noqa: E402
from tqg_client.strategy_catalog_robust import (  # noqa: E402
    RobustEval,
    evaluate_spec,
    load_strategy_descriptions,
)
from tqg_client.strategy_psa_registry import all_psa_specs  # noqa: E402
from tqg_client.strategy_sweep_core import OOS  # noqa: E402

# Also attempt catalog runners for IDs that PSA skips (baseline-only evidence).
import importlib  # noqa: E402

RUNNERS_A = importlib.import_module("tqg_client.strategy_catalog_runners_a")
RUNNERS_B = importlib.import_module("tqg_client.strategy_catalog_runners_b")


def _run_id_for(strategy_id: str) -> str:
    return "catalog_" + strategy_id.lower().replace("-", "_")


def _runner_fn(strategy_id: str):
    name = "run_" + strategy_id.replace("-", "_")
    for mod in (RUNNERS_A, RUNNERS_B):
        fn = getattr(mod, name, None)
        if callable(fn):
            return fn
    return None


def _materialize_run(ev: RobustEval, *, overwrite: bool = False) -> Path:
    run_id = _run_id_for(ev.id)
    root = _REPO / "runs" / run_id
    if root.exists() and any(root.iterdir()) and not overwrite:
        # Refresh artifacts in place
        pass
    else:
        for sub in ("code", "artifacts", "charts", "logs", "inputs"):
            (root / sub).mkdir(parents=True, exist_ok=True)

    if not (root / "run.json").exists():
        state = new_run_state(run_id=run_id, title=f"{ev.id} — {ev.name}", root=root)
        save_run_state(state)
        (root / "flow.json").write_text(
            json.dumps({"turns": [], "updated_at": state.created_at}, indent=2) + "\n",
            encoding="utf-8",
        )
    else:
        state = load_run_state(run_id)

    spec = {
        "workflow": "catalog_robust_batch",
        "strategy_id": ev.id,
        "strategy_name": ev.name,
        "strategy_type": ev.name,
        "symbol": ev.universe,
        "asset_class": ev.asset_class,
        "interval": "1d",
        "oos_start_ts": str(OOS),
        "params": ev.params,
        "selection_mode": ev.selection_mode,
        "psa_status": ev.psa_status,
        "description": ev.description,
        "data_source": "local_catalog",
        "annualization": "crypto=365 equity=252",
        "costs": {"fee_bps": 4.5, "slippage_bps": 5.0, "stress_mult": 2.0},
    }
    (root / "strategy_spec.json").write_text(json.dumps(spec, indent=2) + "\n", encoding="utf-8")

    metrics = {
        "in_sample": {
            "Sharpe": ev.is_metrics.sharpe,
            "MaxDD": ev.is_metrics.max_dd,
            "CAGR": ev.is_metrics.cagr,
            "trades": ev.is_metrics.trades,
            "profit_factor": ev.is_metrics.profit_factor,
        },
        "out_of_sample": {
            "Sharpe": ev.oos_metrics.sharpe,
            "MaxDD": ev.oos_metrics.max_dd,
            "CAGR": ev.oos_metrics.cagr,
            "trades": ev.oos_metrics.trades,
            "profit_factor": ev.oos_metrics.profit_factor,
        },
        "cost_stress_oos_2x": {
            "Sharpe": ev.cost_stress_oos.sharpe,
            "MaxDD": ev.cost_stress_oos.max_dd,
            "CAGR": ev.cost_stress_oos.cagr,
            "trades": ev.cost_stress_oos.trades,
        },
        "robustness_confidence": ev.robustness_confidence,
        "selection_mode": ev.selection_mode,
        "psa_status": ev.psa_status,
        "psa_stable_cells": ev.psa_stable_cells,
        "psa_grid_cells": ev.psa_grid_cells,
    }
    (root / "artifacts" / "metrics.json").write_text(json.dumps(metrics, indent=2) + "\n", encoding="utf-8")
    (root / "artifacts" / "robustness.json").write_text(
        json.dumps(
            {
                "guardrails": ev.robustness_guardrails,
                "confidence": ev.robustness_confidence,
                "params": ev.params,
                "note": ev.note,
                "status": ev.status,
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    code = f'''"""Catalog strategy {ev.id} — selected params from robust batch.

Auto-generated by scripts/tqg_catalog_robust_batch.py
Selection: {ev.selection_mode}
PSA: {ev.psa_status} ({ev.psa_stable_cells}/{ev.psa_grid_cells})
Params: {json.dumps(ev.params)}
"""
from __future__ import annotations

# Evaluation is performed by tqg_client.strategy_catalog_robust / PSA builders.
# Re-run: python scripts/tqg_catalog_robust_batch.py --ids {ev.id}
STRATEGY_ID = {ev.id!r}
PARAMS = {json.dumps(ev.params, indent=2)}
'''
    (root / "code" / "strategy.py").write_text(code, encoding="utf-8")

    report = f"""# {ev.id} — {ev.name}

**Status:** `{ev.status}`  
**Run:** `{run_id}`  
**Universe:** {ev.universe} ({ev.asset_class})  
**Selection:** `{ev.selection_mode}` · PSA `{ev.psa_status}` ({ev.psa_stable_cells}/{ev.psa_grid_cells})  
**Robustness confidence:** {ev.robustness_confidence}/100

## Description

{ev.description}

## Params

```json
{json.dumps(ev.params, indent=2)}
```

## Metrics (OOS cut-off {OOS.date()})

| Period | Sharpe | MaxDD | CAGR | Trades |
|--------|--------|-------|------|--------|
| IS | {ev.is_metrics.sharpe:.3f} | {ev.is_metrics.max_dd:.1%} | {ev.is_metrics.cagr:.1%} | {ev.is_metrics.trades} |
| OOS | {ev.oos_metrics.sharpe:.3f} | {ev.oos_metrics.max_dd:.1%} | {ev.oos_metrics.cagr:.1%} | {ev.oos_metrics.trades} |
| OOS cost×2 | {ev.cost_stress_oos.sharpe:.3f} | {ev.cost_stress_oos.max_dd:.1%} | {ev.cost_stress_oos.cagr:.1%} | {ev.cost_stress_oos.trades} |

## Guardrails

{ev.robustness_guardrails}

## Note

{ev.note or "—"}
"""
    (root / "report.md").write_text(report, encoding="utf-8")

    state.status = "baseline_complete" if ev.status in {"OK", "NO_TRADES", "RUNNER_ONLY"} else "failed"
    if ev.psa_status == "STABLE" and ev.status == "OK":
        state.status = "psa_complete"
    state.symbol = ev.universe
    state.validation_passed = ev.status == "OK" and ev.robustness_confidence >= 40
    state.completed_steps = ["baseline", "psa", "cost_stress"] if ev.status not in {"SKIP", "ERROR"} else []
    state.register_artifact("metrics", "artifacts/metrics.json", "json")
    state.register_artifact("robustness", "artifacts/robustness.json", "json")
    state.register_artifact("report", "report.md", "md")
    save_run_state(state)
    touch_run_index(run_id)
    return root


def _enrich_skip_from_runner(ev: RobustEval, descriptions: dict) -> RobustEval:
    """If PSA skipped, still try catalog runner for full-sample evidence (low confidence)."""
    if ev.status != "SKIP":
        return ev
    fn = _runner_fn(ev.id)
    if fn is None:
        return ev
    try:
        from tqg_client.strategy_sweep_core import SkipStrategy, SweepResult

        res = fn()
        if not isinstance(res, SweepResult) or res.status != "OK":
            if isinstance(res, SweepResult) and res.status == "SKIP":
                ev.note = res.note or ev.note
            return ev
        # Full-sample only — mark as runner_baseline with capped confidence
        ev.status = "RUNNER_ONLY"
        ev.selection_mode = "catalog_runner_full_sample"
        ev.oos_metrics.sharpe = float(res.sharpe or 0)
        ev.oos_metrics.max_dd = float(res.max_dd or 0)
        ev.oos_metrics.cagr = float(res.cagr or 0)
        ev.oos_metrics.trades = int(res.trades or 0)
        ev.is_metrics = ev.oos_metrics  # unknown split
        ev.robustness_guardrails = (
            "catalog runner full-sample only (no IS/OOS split); "
            "fees 4.5bps + slip 5bps; PSA unavailable — confidence capped"
        )
        # Cap confidence: positive sharpe + trade count only
        conf = 10.0
        if (res.sharpe or 0) > 0.5:
            conf += 10
        elif (res.sharpe or 0) > 0:
            conf += 5
        if (res.trades or 0) >= 30:
            conf += 5
        ev.robustness_confidence = min(25.0, conf)
        ev.note = (ev.note + "; " if ev.note else "") + "runner full-sample fallback"
        title, logic = descriptions.get(ev.id, (ev.name, ""))
        ev.description = f"{title}: {logic}".strip(": ")
    except Exception as e:
        from tqg_client.strategy_sweep_core import SkipStrategy

        if isinstance(e, SkipStrategy):
            ev.note = e.reason
        else:
            ev.note = (ev.note + "; " if ev.note else "") + f"runner error: {str(e)[:80]}"
    return ev


def _csv_rows(evals: list[RobustEval]) -> list[dict]:
    rows = []
    for ev in evals:
        rows.append(
            {
                "strategy_id": ev.id,
                "strategy": ev.name,
                "detailed_description": ev.description,
                "universe": ev.universe,
                "asset_class": ev.asset_class,
                "status": ev.status,
                "selection_mode": ev.selection_mode,
                "params": json.dumps(ev.params, sort_keys=True),
                "sharpe_is": round(ev.is_metrics.sharpe, 4),
                "sharpe_oos": round(ev.oos_metrics.sharpe, 4),
                "sharpe": round(ev.oos_metrics.sharpe, 4),  # primary = OOS
                "maxdd_is": round(ev.is_metrics.max_dd, 4),
                "maxdd_oos": round(ev.oos_metrics.max_dd, 4),
                "maxdd": round(ev.oos_metrics.max_dd, 4),
                "cagr_is": round(ev.is_metrics.cagr, 4),
                "cagr_oos": round(ev.oos_metrics.cagr, 4),
                "cagr": round(ev.oos_metrics.cagr, 4),
                "trades_is": ev.is_metrics.trades,
                "trades_oos": ev.oos_metrics.trades,
                "sharpe_oos_cost_stress_2x": round(ev.cost_stress_oos.sharpe, 4),
                "psa_status": ev.psa_status,
                "psa_stable_cells": ev.psa_stable_cells,
                "psa_grid_cells": ev.psa_grid_cells,
                "robustness_guardrails": ev.robustness_guardrails,
                "robustness_confidence": ev.robustness_confidence,
                "run_id": _run_id_for(ev.id),
                "note": ev.note,
            }
        )
    return rows


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--ids", nargs="*", help="Optional subset of strategy IDs (e.g. T-01 CG-05)")
    ap.add_argument("--limit", type=int, default=0, help="Limit number of specs (debug)")
    ap.add_argument("--overwrite", action="store_true")
    ap.add_argument(
        "--out",
        type=Path,
        default=_REPO / "reports" / "catalog_robust_results.csv",
    )
    args = ap.parse_args()

    descriptions = load_strategy_descriptions()
    specs = all_psa_specs()
    if args.ids:
        want = {x.upper() for x in args.ids}
        specs = [s for s in specs if s.id.upper() in want]
    if args.limit and args.limit > 0:
        specs = specs[: args.limit]

    evals: list[RobustEval] = []
    total = len(specs)
    for i, spec in enumerate(specs, 1):
        print(f"[{i}/{total}] {spec.id} {spec.name}...", flush=True)
        ev = evaluate_spec(spec, descriptions)
        if ev.status == "SKIP":
            ev = _enrich_skip_from_runner(ev, descriptions)
        _materialize_run(ev, overwrite=args.overwrite)
        evals.append(ev)
        print(
            f"    -> {ev.status} mode={ev.selection_mode} "
            f"OOS Sharpe={ev.oos_metrics.sharpe:.2f} conf={ev.robustness_confidence}",
            flush=True,
        )

    # Rank OK/RUNNER by OOS sharpe among confidence >= 40, else all
    rows = _csv_rows(evals)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = list(rows[0].keys()) if rows else []
    with args.out.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        w.writerows(rows)

    # Sorted companion table (markdown) next to CSV
    md_path = args.out.with_suffix(".md")
    ranked = sorted(
        evals,
        key=lambda e: (e.oos_metrics.sharpe if e.status in {"OK", "RUNNER_ONLY", "NO_TRADES"} else -999),
        reverse=True,
    )
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    ok_n = sum(1 for e in evals if e.status == "OK")
    lines = [
        f"# Catalog robust batch results",
        "",
        f"> Generated: {now}  ",
        f"> OOS cut-off: {OOS.date()}  ",
        f"> Strategies: {len(evals)} · OK: {ok_n} · "
        f"STABLE PSA: {sum(1 for e in evals if e.psa_status == 'STABLE')}",
        "",
        "| Rank | ID | Strategy | OOS Sharpe | MaxDD | CAGR | Conf | Mode | Status |",
        "|------|-----|----------|------------|-------|------|------|------|--------|",
    ]
    for i, e in enumerate(ranked, 1):
        lines.append(
            f"| {i} | {e.id} | {e.name} | {e.oos_metrics.sharpe:.2f} | "
            f"{e.oos_metrics.max_dd:.1%} | {e.oos_metrics.cagr:.1%} | "
            f"{e.robustness_confidence:.0f} | {e.selection_mode} | {e.status} |"
        )
    md_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"\nWrote {args.out}")
    print(f"Wrote {md_path}")
    print(f"Materialized {len(evals)} runs under runs/catalog_*")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
